#!/usr/bin/env python3
"""Generate docs/RUNTIME-TYPES.md and .zh-CN.md: every script-visible type the
pinned runtime defines, by namespace, names only.

Reads checkouts of makepad and Octoscript-Makepad at the revisions App Hub's
card-host pins (the runtime the gate vouches for) and harvests the four ways a
type is registered for scripts. SCRIPT-API documents the supported subset;
this page says what resolves at all.

usage: gen_runtime_types.py <makepad checkout> <octoscript-makepad checkout> <makepad rev> <osm rev>"""
import os, re, subprocess, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEF = re.compile(r"mod\.([A-Za-z_][A-Za-z0-9_.]*)\s*="); API = re.compile(r"#\((\w+)::(?:script_api|script_component|register_widget)\(vm\)\)")
STD = re.compile(r"^\s*([A-Z]\w*):\s*mod\.std\.set_type_default", re.M); VAL = re.compile(r"set_script_value_to_api!\(vm,\s*([A-Za-z_][A-Za-z0-9_.]*)\)")
def head(p): return subprocess.run(["git", "-C", p, "rev-parse", "HEAD"], capture_output=True, text=True, check=True).stdout.strip()
def harvest(root, subdirs):
    names = set()
    for sub in subdirs:
        for d, _, fs in os.walk(os.path.join(root, sub)):
            for f in fs:
                if f.endswith(".rs"):
                    t = open(os.path.join(d, f), encoding="utf-8", errors="replace").read()
                    for rx in (DEF, API, STD, VAL): names.update(rx.findall(t))
    return names
def main():
    mk, osm, mkrev, osmrev = sys.argv[1:5]
    for p, want in ((mk, mkrev), (osm, osmrev)):
        if head(p) != want: sys.exit(f"{p} is at {head(p)}, expected {want}")
    names = harvest(mk, ["widgets/src", "platform/script", "draw/src", "platform/src"]) | harvest(osm, ["crates"])
    dotted = {n for n in names if "." in n}; bare_covered = {n.rsplit(".", 1)[-1] for n in dotted}
    groups = {}
    for n in sorted(dotted): ns, leaf = n.rsplit(".", 1); groups.setdefault(ns, []).append(leaf)
    loose = sorted(n for n in names if "." not in n and n not in bare_covered and n[:1].isupper())
    for lang in ("en", "zh"):
        if lang == "en":
            L = ["# Runtime types", "", "English | [简体中文](RUNTIME-TYPES.zh-CN.md)", "",
                 f"Every type name a script can resolve in the runtime OctoSense desktop 0.1.0-rc.1 ships — makepad `{mkrev[:8]}` (widgets prelude, draw, script std) and Octoscript-Makepad `{osmrev[:8]}` — by namespace, names only. **A name resolving is not a supported API:** [SCRIPT-API](SCRIPT-API.md) documents the widgets and methods a store app should use, with their grants and limits; a type listed only here may be undocumented, system-only or unfinished. `makepad/libs/*` is not included, because the shipped runtime does not link it.", "",
                 "Generated by `tools/gen_runtime_types.py` from the pinned sources; regenerate when App Hub's `card-host` pins move. Do not edit by hand.", ""]
        else:
            L = ["# 运行时类型", "", "[English](RUNTIME-TYPES.md) | 简体中文", "",
                 f"OctoSense 桌面版 0.1.0-rc.1 所带运行时——makepad `{mkrev[:8]}`（控件预置、draw、脚本标准库）和 Octoscript-Makepad `{osmrev[:8]}`——中脚本可以解析的全部类型名，按命名空间列出，只有名称。**能解析不等于受支持的 API**：[SCRIPT-API](SCRIPT-API.md) 记录了商店应用应当使用的控件和方法及其授权与限制；只出现在本页的类型可能没有文档、仅限系统应用或尚未完成。`makepad/libs/*` 未收录，因为发行的运行时并不链接它。", "",
                 "由 `tools/gen_runtime_types.py` 从锁定的源码生成；App Hub 的 `card-host` 锁定版本变动时请重新生成。不要手工修改。", ""]
        for ns, leaves in groups.items():
            L += [f"## `{ns}` ({len(leaves)})" if lang == "en" else f"## `{ns}`（{len(leaves)}）", "", ", ".join(f"`{x}`" for x in leaves), ""]
        if loose:
            L += ["## Registered without a namespace" if lang == "en" else "## 未带命名空间注册的类型", "", ", ".join(f"`{x}`" for x in loose), ""]
        out = os.path.join(ROOT, "docs", "RUNTIME-TYPES.md" if lang == "en" else "RUNTIME-TYPES.zh-CN.md")
        open(out, "w", encoding="utf-8").write("\n".join(L)); print("wrote", out, "-", sum(len(v) for v in groups.values()), "dotted +", len(loose), "loose names")
main()
